src/checks/graphiteWorking.check.js, test/graphiteworking.spec.js
Using graphite's `summarize` function gives you 2 datapoints, one for the left-most part of the axis
and the other for the right-most. These are averaged out to give a straight line on a graph, but don't
represent accurate values, for example if the latest value is 0 but the rest are high, you won't see
the dropoff using `summarize` until the high data is over the bounds of the average. Conversely, if its
at 0 for a while, and new non-zeo data comes in, again this won't be visible or accurate for a while.
The purpose of this healthcheck is to simply check if the latest entries are non-zero. So we can potentially
just get the latest value in the timeseries and check that... a small problem herein lies that the data
in graphite can be out of sync from real world. From eye balling as much as …
=> fix: manually summarise datapoints for graphiteWorking check

src/checks/json.check.js, test/fixtures/config/jsonCheckFixture.js, test/json.check.spec.js
This will allow us to have checks for APIs that require API Keys for their
Good to go endpoints.
=> Allow fetch to be configured for the JSON check.

src/checks/index.js
Seems I forgot to add these in #31 & #32 
ronseal
=> Ensure new cloudWatch checks are exported publically

README.md, src/checks/graphiteThreshold.check.js, test/graphiteThreshold.check.spec.js
Also, change logic so check fails if _any_ metric goes above (or below) the threshold, rather than if the average goes above (or below) - seems to be more in the spirit of what a user would want
=> Handle empty series for graphiteThreshold

src/checks/graphiteThreshold.check.js, test/graphiteThreshold.check.spec.js
cc @ironsidevsquincy 
Transpired that `minimumBelow` was not available in the version of Graphite that we are using and health checks using `direction: 'below'` to set a lower threshold would fail regardless.
Now uses `maxSeries` and `minSeries` (for upper and lower thresholds respectively) then examines a series of data points and if any exceed the threshold then health check will fail.
Null values are disregarded (value has to be non-null and exceeding the threshold):
=> Amend: Graphite threshold check

src/checks/graphiteSpike.check.js, src/checks/graphiteThreshold.check.js, src/checks/graphiteWorking.check.js
Hopefully this will help us to understand better any issues we have with the checks, such as the internal Graphite going down.
=> Add error logging for the Graphite spike and threshold checks

src/checks/responseCompare.check.js, test/fixtures/config/responseCompareFixture.js, test/responseCompare.check.spec.js
1. specify headers (e.g., backend key)
2. function to "normalize" response (e.g., timestamps) before comparison
=> add some comparison options

src/checks/cloudWatchThreshold.check.js, test/cloudWatchThreshold.check.spec.js
further to my earlier PR, CloudWatch is still not really playing ball. I'm seeing similar issues on other `samplePeriod`s (only for some metrics though, weirdly). Making the window equal to 1.5x the `samplePeriod` seems to have done the trick though 👍 
(bonus: fixed typo ✨ )
=> CloudWatch sample window fix v2

src/checks/graphiteSpike.check.js, src/checks/graphiteThreshold.check.js, src/checks/graphiteWorking.check.js
Also updated to use `.test` instead of `.match` for testing against the regex and fixed it to make sure `next` was actually _prepended_.
=> Fix slightly misleading graphite check error

src/checks/graphiteSpike.check.js, src/checks/graphiteThreshold.check.js, src/checks/graphiteWorking.check.js
Some checks have them formatted as queries starting like this: `sumSeries(next.heroku.etc)`
=> Don't explicitly check for 'next' being the first thing in the string

.gitignore, Makefile, README.md, package.json, src/checks/check.js, src/checks/index.js, src/checks/keenThreshold.check.js, test/fixtures/config/keenThresholdFixture.js, test/keenThreshold.check.spec.js
This will allow us to take the healthcheck stuff outside of beacon, and into the apps where it is most relevant.
Warning: Think about what threshold/timeframe to use to avoid a noisy check. Often to check something is working, it's fine to check it's happened once or twice.
* Create a new type of healthcheck for keen queries
* Add an 'officeHoursOnly' property of checks, which always returns green outside of office hours. This is useful for some keen queries (e.g. b2b or IE usage based), and @geek-caroline has some use for it in Conversion land.
=> Keen health checks

src/checks/keenThreshold.check.js
🐿 v2.7.0
Keen proxy has some [clever TTL setting](https://github.com/Financial-Times/keen-proxy/blob/master/vcl/main.vcl#L54) based on the query. Because we're not setting any intervals, I _think_ it defaults to 30mins, which obviously isn't great for a healthcheck!
Force it to be 5 mins.
=> Custom TTL for keen healthchecks

src/checks/keenThreshold.check.js
Until the first run, the check should be OK.
This is because it could be failing for 10 minutes until it's run, causing it to alert in all the various places.
Example below of the current setup alerting after a dyno restart.
=> Defaut Keen to passed

src/checks/keenSpike.check.js
This better matches up with how `relTime` works as far as I understand it.
=> Make baseline comparison look backwards

src/checks/keenSpike.check.js, src/checks/keenThreshold.check.js
In an attempt to reduce the cost of Keen, reduce the default interval that the healthchecks run at to 1 hour.
=> Update keen threshold interval

Makefile, package.json, src/checks/graphiteThreshold.check.js, test/graphiteThreshold.check.spec.js
e.g. instead of:
next.heroku.front-page.sections.*.articles.min
we see:
next.heroku.front-page.sections.topStories.articles.min and next.heroku.front-page.sections.technology.articles.min
🐿 v2.9.0
=> tell us which specific targets (metrics) fail for wildcarded targets

src/checks/graphiteThreshold.check.js, src/checks/graphiteWorking.check.js, test/fixtures/config/graphiteWorkingFixture.js, test/graphiteThreshold.check.spec.js, test/graphiteworking.spec.js
- get graphiteThreshold to ignore nulls
- add comments to encourage the use of graphiteWorking for nulls
- refactor graphiteWorking to better deal with wildcarded metrics and to
fail when the last three consecutive datapoints are nulls
=> deal with nulls in metric data

src/checks/graphiteWorking.check.js
This check originally had a time option that could be passed in and default of 15 mins. Reinstating these to ensure consistent functionality.
This is where it was changed - https://github.com/Financial-Times/n-health/pull/93/files#diff-da2131d47c111725f59bb95bb91be19eR32
=> Adding back override to graphiteWorking

src/checks/graphiteSpike.check.js
This is in relation to intermittent healthcheck notifications received in the #next-support slack channel. 
Related links: 
- https://github.com/Financial-Times/n-express/pull/476
- https://github.com/Financial-Times/next-myft-api/blob/master/server/libs/health-checks/graphite.js
- https://github.com/Financial-Times/n-health#graphitespike
- https://github.com/Financial-Times/next-myft-api/pull/736
- https://heimdall.in.ft.com/system?code=next-myft-api
- https://runbooks.in.ft.com/next-myft-api
- https://ft-next-myft-api.herokuapp.com/__health
=> Show spike data in error message

src/checks/graphiteSpike.check.js
Just a braimdump of my interpretation of the graphite spike check.
=> Added an explanation of the graphite spike check.

test/fixtures/serviceRegistryFixture.json
We're in the process of decommissioning `next-signup` and that means that this service is no longer used.
🐿 v2.10.1
=> Remove reference to next-signup-proxy

src/checks/check.js
The healthcheck standards specify that each individual check requires an id. This adds an id to the check output as an optional argument.
[Healthcheck standards](https://docs.google.com/document/d/18hefJjImF5IFp9WvPAm9Iq5_GmWzI9ahlKSzShpQl1s/edit#)
It may be worth making it required [here](https://github.com/Financial-Times/n-health/pull/122/files#diff-96a27ee154396c4250170560d265b13cR17) but it would be a more significant breaking change
=> Add id field to outputted checks

.circleci/config.yml, test/startup.spec.js
This PR is a part of [this Ops Cops ticket](https://financialtimes.atlassian.net/browse/NOPS-388).
>We would like teams to be notified when nightly builds fail for the apps they own.
This repo was chosen for checking the very beginning of this implementation.
We would like to check whether the failed nightly build notification will be sent correctly.
The test notification will be sent to **Ops Cops team channel** at midnight when nightly build happens.
The circleci build-test for this PR is failed because of this failing test 01049ce, which is a part of this test.
=> Ops cops: failed Nightly build notification test

.circleci/config.yml, test/startup.spec.js
Reverts Financial-Times/n-health#124
As I posted in platform team channel, https://financialtimes.slack.com/archives/C3TJ6KXEU/p1599753860065800
I confirmed the alert was sent correctly last night.
I'm going to revert this test commits.
=> Revert "Ops cops: failed Nightly build notification test"

.circleci/config.yml
Ops Cops would like teams to be notified when nightly builds fail for the apps they own [Jira](https://financialtimes.atlassian.net/browse/NOPS-388).
This is the improved version of #124 without a failing test.
This repo's failed nightly build notifications are sent to Ops Cops team channel.
**TODO in the future**
- Change `TEAM_SLACK_WEBHOOK` in the vault to the team channel's webhook from Ops Cops' one.
=> Add failed nightly build slack notification in Circle config

README.md, src/checks/graphiteSpike.check.js, test/graphiteSpike.check.spec.js
We discovered that there is a situation where we get null values for Sample and Baseline from Graphite, which we aren't handling [here](https://github.com/Financial-Times/n-health/blob/a3cb60053b905fb140607cb84da0029b65a0a99b/src/checks/graphiteSpike.check.js#L98-L100). If Sample and Baseline are both nulls, these [conditions](https://github.com/Financial-Times/n-health/blob/a3cb60053b905fb140607cb84da0029b65a0a99b/src/checks/graphiteSpike.check.js#L104-L105) will be false, and `ok` will also be false. This PR adds [transformNull](https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.transformNull) to the graphite query and an additional check for null values. See [discussion](https://financialtimes.slack.com/archives/C3QLCEZKP/p1620737945147600). …
=> NOPS-817- Handle Sample and Baseline null values.

src/checks/graphiteSpike.check.js, test/graphiteSpike.check.spec.js
Graphite is falsely erroring when both baseline and sample are zero, see [issue](https://github.com/Financial-Times/n-health/issues/148). 
This PR adds a check for a baseline of 0 to the check that was recently added for null, and will update the baseline as 1 if that's the case. This is necessary as it is a divisor.
=> Added check for 0 baseline as it's used as a divisor

src/checks/graphiteThreshold.check.js, test/graphiteThreshold.check.spec.js
In dev huddle today I spoke about the fact that historically we don't alert based on null data.
Some people mentioned this may be due to the reliability of Graphite in the past. I'd like to log the rate that we encounter null data as part of this threshold check with the potential to reverse the behaviour if we find that it's infrequent.
=> [NOPS-985] Log null data in GraphiteThreshold check

src/checks/graphiteThreshold.check.js, test/graphiteThreshold.check.spec.js
Companion to #164 
Graphite datapoints are values stored with their timestamp. But, if there are no events during that timestamp, the value will be `null` and not `0`, ie denoting explicit lack of a value. (https://graphite.readthedocs.io/en/latest/terminology.html#graphite-terminology). So in some cases `null` is an expected - and even desirable value. For example if we're checking the `error.count` then `0` is ideal as that means no errors are occurring. 
Things get a little bit interesting when we look at `asPercent` and `divideSeries`. Those two graphite functions are used in the same way - we take a `sum of errors in _time_` and a `sum of successes in _time_` and we either express the result as a percentage or division result. I think the desired metrics is the ratio of errors to …
=> NOPS-1034 added threshold handling for asPercent and divideSeries

src/checks/graphiteSpike.check.js
Next-health has this health check: https://github.com/Financial-Times/next-health/blob/main/server/config/health-checks/platform.js. It is very flappy. The flaps are ephemeral - such at that if you click on "healthcheck source" in Heimdall immediately after it goes red, you'll get a "all healthy" source logs. As we can't see what numbers are triggering the flaps, it is really difficult - bordering on impossible - to fix the source of the problem. We are hoping that this log will help us **see** what is wrong when the flaps happen and act accordingly. 
Q: Why just graphiteSpike, and not all of the checks?
A: This has a potential to be noisy and expensive. I would love to add this to all of the checks, but I want to use this one as a trial to see if it actually does give the information we …
=> FTDCS-33 added logs to failing graphiteSpike checks

.circleci/config.yml
Add the caret to the npm version to fix a common problem in the build.
=> FTDCS-152 - Fix CircleCI configuration file

.mocharc.js, package-lock.json, package.json, test/cloudWatchAlarm.check.spec.js, test/cloudWatchThreshold.check.spec.js, test/pingdom.check.spec.js
- Update testing packages Sinon, Mocha & Chai.
- Create some stubs inside the beforeEach, to avoid interferences between tests -> tests isolation
- Fix a missing `done` parameter.
=> FTDCS-196 - Update testing

src/checks/fastlyKeyExpiration.check.js, src/checks/index.js, test/fastlyKeyExpiration.check.spec.js
We should add a check type to n-health which verifies Fastly keys using https://api.fastly.com/tokens/self:
- alert if the key expires in the next week or two
- alert if the key has a null expiry date
=> FTDCS-196 - Fastly key expiration check merge

README.md, src/checks/fastlyKeyExpiration.check.js
The panic guide is the same for any fastly key, so there is no point to repeat the same in each configuration health check.
Anyway, there is the option to set a custom panic guide, just in case.
=> FTDCS-196 - Added default panic guide for Fastly key expiration check

README.md, src/checks/fastlyKeyExpiration.check.js, test/fastlyKeyExpiration.check.spec.js
Add link to the README to the documentation for the [Healthcheck standard](https://docs.google.com/a/ft.com/document/d/18hefJjImF5IFp9WvPAm9Iq5_GmWzI9ahlKSzShpQl1s/edit#heading=h.pphr52zg8c2e) 
Change Fastly key expiration check message to comply with the standard.
Change test according the new change.
=> FTDCS-196 - Comply with the standards

README.md, secrets.js, src/checks/herokuLogDrain.check.js, src/checks/index.js, test/herokuLogDrain.check.spec.js
This adds a new check type which can validate that a Heroku app has a
valid log drain configured. We're validating against the configuration
[documented here](https://tech.in.ft.com/tech-topics/logging/splunk/logging-from-heroku#configuration).
We'll enable this check by default in n-express _if_ the app has the
latest dependencies and the migration environment flag.
One potentially contentious decision is use of the `HEROKU_APP_ID`
environment variable. Not all of our apps have this, and we'll need the
value in Heroku to be set to the _specific_ app so different per region.
I believe the ones that have this value are using this Heroku beta?
https://devcenter.heroku.com/articles/dyno-metadata
We have two options to resolve this:
1. We enable this beta for all our apps
2. We attempt to …
=> Add a Heroku log drain check type

package-lock.json, package.json, src/checks/check.js
The use of n-raven in this library is causing us some issues rolling out
log drains. As part of the move to log drains we want to consistently
log errors which crashed the application and we're having to do this
work in n-raven.
While n-raven is included in both n-health and n-express, it's easy for
the versions to get out of sync. If this happens then the Sentry Raven
client is installed twice, which (because we're relying on a singleton)
will actually remove any custom unhandled exception handling code and
revert to the default Sentry handler with no error logging.
This is really bad and it could happen quite easily without anyone
knowing.
We decided that the best approach would be to remove Sentry logging from
n-health entirely and rely only on the errors we log to Splunk. A later …
=> Remove n-raven

src/checks/herokuLogDrain.check.js, test/herokuLogDrain.check.spec.js
FTDCS-257
Jira card: https://financialtimes.atlassian.net/jira/software/c/projects/FTDCS/boards/1426?modal=detail&selectedIssue=FTDCS-257
This PR supersedes https://github.com/Financial-Times/n-health/pull/200
[Tech Hub: Logging to Splunk from Heroku](https://tech.in.ft.com/tech-topics/logging/splunk/logging-from-heroku#configuration) has recently changed the command (via this [`tech-hub` PR](https://github.com/Financial-Times/tech-hub/pull/742/files#diff-acb03fb0bb145aa15ed23cbd115db7496e1de8426491400ae0582104675bd834)) to configure to log drains.
**From:**
`$ heroku drains:add 'https://x:$SPLUNK_HEC_TOKEN@http-inputs-financialtimes.splunkcloud.com/services/collector/raw?source=$SYSTEM_CODE&sourcetype=heroku&host=$HEROKU_APP_URL&channel=$SPLUNK_CHANNEL_ID' -a $HEROKU_APP_NAME`
**To:**
`$ …
=> Modify Heroku log drain check to ensure absence of sourcetype param

src/checks/herokuLogDrain.check.js, test/herokuLogDrain.check.spec.js
This PR amends the panic guide text in the Heroku log drain check so that it does not use Markdown which is not supported in the Heimdall GUI, e.g.
https://heimdall.ftops.tech/system?code=next-houston
=> Fix unusable Markdown in Heroku log drain check panic guide text

src/checks/herokuLogDrain.check.js, test/herokuLogDrain.check.spec.js
FTDCS-299
Jira card: https://financialtimes.atlassian.net/jira/software/c/projects/FTDCS/boards/1426?modal=detail&selectedIssue=FTDCS-299
Ref. [Slack chat](https://financialtimes.slack.com/archives/C02B89GEQHF/p1661528764824409) in which it was identified that the Heroku log drains for next-ads-api incorrectly prefixed its `host` param value with `https:/` - Step 2.3 of the [migration guide](https://financialtimes.atlassian.net/wiki/spaces/DS/pages/7883555001/Migrating+an+app+to+Heroku+log+drains#Step-2.3) states that the `host` param value should be:
> The Heroku app URL excluding the protocol and path (e.g. ft-next-article-eu.herokuapp.com)
- [Stack Overflow: javascript regular expression to not match a word](https://stackoverflow.com/questions/6449131/javascript-regular-expression-to-no …
=> Add Heroku log drain host format check

package-lock.json, package.json
This PR is in relation to https://github.com/Financial-Times/next-preflight/pull/645, which resulted in `next-preflight` consuming a mixture of `isomorphic-fetch` v2 (which consumes `node-fetch` v1) and v3 (which consumes `node-fetch` v2).
The working assumption is that this mixture of `node-fetch` versions had been present before now but that the specific composition and ordering of dependencies meant that an instance of `node-fetch` v1 was always identified first and consequently the version that was employed by the code but that the changes in the above-mentioned PR meant that `node-fetch` v2 was the version employed by the code and that `next-preflight` had not yet been updated to accommodate any major breaking changes.
As a result, this caused …
=> Upgrade node-fetch ^1.5.1 -> ^2.6.7

src/checks/herokuLogDrain.check.js
The [README](https://github.com/Financial-Times/n-health) for this repo says that the options for check objects include:
> `interval`: time between checks in milliseconds or any string compatible with [ms](https://www.npmjs.com/package/ms) [default: 1minute]
We are currently experiencing the below error for several apps:
> "Heroku log drain configuration check failed to fetch data: heroku responded with a 429 status code"
It seems unnecessary for this to be checked at one minute intervals because it is not a condition that will change will a high amount of regularity and given the effect it is having on contributing to reaching our Heroku API key limit, it seems judicious to reduce its impact.
Perhaps one day intervals is too extreme and happy to take a steer on what might be a more …
=> Increase interval between Heroku log drain health checks

.circleci/config.yml, package-lock.json, package.json
Automatically ran via Platforms' [migration script](https://github.com/Financial-Times/platform-scripts/blob/464d56876a27742dbdee2713a31266cc268ebfe3/upgrade-node-18/upgrade-node-18.ts)
[CPP-1562](https://financialtimes.atlassian.net/browse/CPP-1562)
[CPP-1562]: https://financialtimes.atlassian.net/browse/CPP-1562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CPP-1562: Update to Node 18

src/checks/graphiteThreshold.check.js, src/checks/graphiteWorking.check.js, test/graphiteThreshold.check.spec.js
One of the reasons we have a log level of `warn` is because we traditionally over-logged with a level of `info`. I'm switching some of the info-level logs in our dependencies to `debug` so that you can opt in when debugging an app but we don't flood Splunk.
=> Soften the logging

package-lock.json, package.json, src/checks/check.js, src/checks/cloudWatchAlarm.check.js, src/checks/cloudWatchThreshold.check.js, src/checks/fastlyKeyExpiration.check.js, src/checks/graphiteSpike.check.js, src/checks/graphiteThreshold.check.js, src/checks/graphiteWorking.check.js, test/fastlyKeyExpiration.check.spec.js, test/graphiteThreshold.check.spec.js
This replaces n-logger usage with Reliability Kit logger. It's a breaking change because the module now logs to  rather than sending logs directly to Splunk. This should be a safe upgrade for most Customer Products apps.
Part of [CPREL-668](https://financialtimes.atlassian.net/browse/CPREL-668).
[CPREL-668]: https://financialtimes.atlassian.net/browse/CPREL-668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Breaking: replace n-logger with Reliability Kit logger

package-lock.json, package.json, src/checks/cloudWatchThreshold.check.js, src/checks/fastlyKeyExpiration.check.js
Slight side-track, but oh well, here we are! We don't need Moment for these use-cases, and they're probably clear enough without needing any date manipulation/parsing libraries.
We can add/subtract using regular date. The following code to subtract seconds is equivalent:
```js
function runMoment(samplePeriod) {
const timeWindow = samplePeriod * 1.5;
const now = moment();
const startTime = now.subtract(timeWindow, 'seconds');
return startTime.toISOString();
}
function runDate(samplePeriod) {
const timeWindowInMs = (samplePeriod * 1.5) * 1000;
const now = new Date();
const startTime = new Date(now.getTime() - timeWindowInMs);
return startTime.toISOString();
}
console.log("moment", runMoment(60 * 5));
console.log("js", runDate(60 * 5));
```
The following code to add two weeks to a date is …
=> Remove moment

test/graphiteSpike.check.spec.js
See https://github.com/Financial-Times/n-health/security/code-scanning/1
=> Properly escape periods in hostname regexp

.npmignore, .snyk, package-lock.json, package.json
In mid-December 2024 we will be letting our Snyk contract expire. We'll
be moving to GitHub Advanced Security as an alternative.
This PR is an attempt to get ahead of the deadline. Considering how out
of date some of our Snyk implementations are, and that we rarely take
the time to merge the PRs, we think it's fine to remove it way ahead of
time.
If you want an interrim solution, enable Dependabot Security updates for
this repository by visiting the following page and clicking 'Enable' next
to 'Dependabot security updates':
https://github.com/Financial-Times/n-health/settings/security_analysis
You're also free to ignore this PR and do the work yourself closer to
the deadline. Cyber will be doing some broader comms later in the year.
This PR was automated, please take a little extra care …
=> chore: remove snyk [automated]

package-lock.json, package.json, test/aggregate.check.spec.js, test/cloudWatchAlarm.check.spec.js, test/cloudWatchThreshold.check.spec.js, test/fastlyKeyExpiration.check.spec.js, test/healthchecks.spec.js, test/json.check.spec.js, test/responseCompare.check.spec.js, test/startup.spec.js, test/string.check.spec.js
[Chai v5 is ESM-only](https://www.chaijs.com/releases/#v5.0.0) which would be a really big migration. We're not doing any complicated assertions in the tests here so I think it makes sense to just switch to the built-in [`assert`](https://nodejs.org/api/assert.html) module. We get to drop a dependency (just under 1MB) and I think assert is easier to understand anyway.
=> Remove Chai

.github/dependabot.yml
This ensures that `package.json` is bumped instead of only `package-lock.json`.
=> build: set versioning strategy
