Financial-Times/n-health

- main.js
- package.json
Otherwise this can't really be used easily with next express @aintgoin2goa
> added helpers to get standalone healthchecks

- Makefile
- src/checks/graphiteSpike.check.js
- test/graphiteSpike.check.spec.js
> added ability to read graphite spikes from alternative graphite services

- src/checks/graphiteSpike.check.js
@wheresrhys can i try this please?
Example here - https://github.com/Financial-Times/spoor-api/pull/81/files
> Ability to override the summarize and series functions

- main.js
@wheresrhys assume this is a mistake?
> ype -> type

- .gitignore
- circle.yml
- n.Makefile
- package.json
> Automatic releases

- src/checks/string.check.js
- test/fixtures/config/stringCheckFixture.js
- test/string.check.spec.js
This can be used for service that implement the FT __gtg standard.
> Include a plain/text response string check

- test/fixtures/serviceRegistryFixture.json
> Remove: next-rtcl-email-api references

- README.md
> Update Cloudwatch readme

- package.json
- src/checks/aggregate.check.js
- src/checks/check.js
- src/checks/graphiteWorking.check.js
- src/checks/memory.check.js
- src/checks/status.js
> prevent overriding of important error handling behaviour

- src/checks/graphiteThreshold.check.js
- test/graphiteThreshold.check.spec.js
> Remove: minSeries + maxSeries in threshold check

- test/fixtures/serviceRegistryFixture.json
> Remove: Concepts API from test fixtures

- test/fixtures/serviceRegistryFixture.json
> Remove: myFT Email Generator from test fixtures

- src/checks/graphiteThreshold.check.js
> More appropriate output messages for graphite metric threshold checks

- package.json
> Update n-gage stuff

- src/checks/graphiteWorking.check.js
Better support for Splunk HEC format.
> Tidy up logging

- .circleci/config.yml
- circle.yml
> circle2 migration

- src/checks/graphiteSumThreshold.check.js
- src/checks/index.js
- test/fixtures/config/graphiteSumThresholdFixture.js
- test/graphiteSumThreshold.check.spec.js
> Adding new check for graphite threshold sum

- src/checks/graphiteThreshold.check.js
- test/graphiteThreshold.check.spec.js
> fix the test for nulls :blush:

- src/checks/graphiteSpike.check.js
- src/checks/graphiteThreshold.check.js
- src/checks/graphiteWorking.check.js
- test/graphiteSpike.check.spec.js
Part of https://github.com/Financial-Times/next/issues/170.
This will start updating our apps to read from the new system.
We will release a beta initially to ensure the change is good.
> Point Graphite checks at the new system

- src/checks/graphiteSpike.check.js
This error is related to this change #149
> Fix Cannot read property ‘datapoints’ of undefined

- README.md
- src/checks/index.js
Add documentation and change the check type for a better further implementation.
> FTDCS-196 - Improve Fastly key expiration check

- ft.yml
> Remove ft.yml
